config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :yazars, :path=>"yazarlar"
  resources :kitaps, :path=>"kitaplar"
  root "kitaps#index"
  resources :kitaps, :path =>"kitaplar" do
    put "like", to: "kitaps#like"
    end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kitap.rb
class Kitap < ApplicationRecord
  has_attached_file :resim, styles: { medium: "600x400>", thumb: "600x400>" }, default_url:
"/images/:style/missing.png" 
    validates_attachment_content_type :resim, content_type: /\Aimage\/.*\z/
    belongs_to :user
has_one :like, :dependent => :destroy
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :kitap
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :kitaps
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/yazar.rb
class Yazar < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kitaps_controller.rb
class KitapsController < ApplicationController
  before_action :set_kitap, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :destroy]
  before_action :kontrol, only: [:edit, :update, :destroy]
  # GET /kitaps
  # GET /kitaps.json
  def index
    @kitaps = Kitap.all
  end

  # GET /kitaps/1
  # GET /kitaps/1.json
  def show
  end

  # GET /kitaps/new
  def new
    @kitap = Kitap.new
  end

  # GET /kitaps/1/edit
  def edit
  end
  def like
    @like=Like.find_by(kitap:params[:kitap_id])
    @like.sayi=@like.sayi+1
    @like.save
    respond_to do |format|
    format.js {@like}
    format.json
    end
    end
  # POST /kitaps
  # POST /kitaps.json
  def create
    @kitap = Kitap.new(kitap_params)
    @kitap.user=current_user
    Like.create(kitap: @kitap, sayi:0)
    respond_to do |format|
      if @kitap.save
        format.html { redirect_to @kitap, notice: 'Kitap was successfully created.' }
        format.json { render :show, status: :created, location: @kitap }
      else
        format.html { render :new }
        format.json { render json: @kitap.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kitaps/1
  # PATCH/PUT /kitaps/1.json
  def update
    respond_to do |format|
      if @kitap.update(kitap_params)
        format.html { redirect_to @kitap, notice: 'Kitap was successfully updated.' }
        format.json { render :show, status: :ok, location: @kitap }
      else
        format.html { render :edit }
        format.json { render json: @kitap.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kitaps/1
  # DELETE /kitaps/1.json
  def destroy
    @kitap.destroy
    respond_to do |format|
      format.html { redirect_to kitaps_url, notice: 'Kitap was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def kontrol
    if @kitap.user!=current_user
    redirect_to root_url, notice: 'Yetkiniz yok'
    end
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_kitap
      @kitap = Kitap.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def kitap_params
      params.require(:kitap).permit(:isim, :ozet, :resim)
    end
end

app/controllers/yazars_controller.rb
class YazarsController < ApplicationController
  before_action :set_yazar, only: [:show, :edit, :update, :destroy]

  # GET /yazars
  # GET /yazars.json
  def index
    @yazars = Yazar.all
  end

  # GET /yazars/1
  # GET /yazars/1.json
  def show
  end

  # GET /yazars/new
  def new
    @yazar = Yazar.new
  end

  # GET /yazars/1/edit
  def edit
  end

  # POST /yazars
  # POST /yazars.json
  def create
    @yazar = Yazar.new(yazar_params)

    respond_to do |format|
      if @yazar.save
        format.html { redirect_to @yazar, notice: 'Yazar was successfully created.' }
        format.json { render :show, status: :created, location: @yazar }
      else
        format.html { render :new }
        format.json { render json: @yazar.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /yazars/1
  # PATCH/PUT /yazars/1.json
  def update
    respond_to do |format|
      if @yazar.update(yazar_params)
        format.html { redirect_to @yazar, notice: 'Yazar was successfully updated.' }
        format.json { render :show, status: :ok, location: @yazar }
      else
        format.html { render :edit }
        format.json { render json: @yazar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /yazars/1
  # DELETE /yazars/1.json
  def destroy
    @yazar.destroy
    respond_to do |format|
      format.html { redirect_to yazars_url, notice: 'Yazar was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_yazar
      @yazar = Yazar.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def yazar_params
      params.require(:yazar).permit(:isim)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kitaps_helper.rb
module KitapsHelper
end

app/helpers/yazars_helper.rb
module YazarsHelper
end

app/views/kitaps/_form.html.erb
<%= form_with(model: kitap, local: true) do |form| %>
  <% if kitap.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(kitap.errors.count, "error") %> prohibited this kitap from being saved:</h2>

      <ul>
      <% kitap.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :isim %>
    <%= form.text_field :isim %>
  </div>

  <div class="field">
    <%= form.label :ozet %>
    <%= form.text_area :ozet %>
  </div>

  <div class="field">
    <%= form.label :sayfa %>
    <%= form.number_field :sayfa %>
  </div>
  <div class="field">
  <%= form.label :resim %>
  <%= form.file_field :resim %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/kitaps/edit.html.erb
<h1>Editing Kitap</h1>

<%= render 'form', kitap: @kitap %>

<%= link_to 'Show', @kitap %> |
<%= link_to 'Back', kitaps_path %>

app/views/kitaps/index.html.erb
<p id="notice"><%= notice %></p>

<% @kitaps.each do |kitap| %>
    <div class="container-fluid">
        <div class="row">
            <div class="col">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title"> <%= kitap.isim %> </h5>
                        <p class="card-text"><%= image_tag kitap.resim.url(:thumb) if kitap.resim? %></p>
                        <h6 class="card-subtitle mb-2 text-muted"><%= kitap.ozet %></h6>
                        <%=kitap.user.email%>
                        <%= link_to 'Show', kitap %>
                        <%= link_to 'Edit', edit_kitap_path(kitap) %>
                        <%= link_to 'Destroy', kitap, method: :delete, data: { confirm: 'Are you sure?' } %>
                    </div>
                </div>
            </div>
        </div>
        <br/>
<% end %>
<%= link_to 'New Kitap', new_kitap_path %>

app/views/kitaps/like.js.erb
$("#like").html("beğendin"+"<%=@like.sayi%>")

app/views/kitaps/new.html.erb
<h1>New Kitap</h1>

<%= render 'form', kitap: @kitap %>

<%= link_to 'Back', kitaps_path %>

app/views/kitaps/show.html.erb
<p id="notice"><%= notice %></p>
<section class="blog-post-area section-margin">
    <div class="container">
      <div class="row">
        <div class="col-lg-8">
            <div class="main_blog_details">
                
<%= image_tag @kitap.resim.url(:medium) if @kitap.resim? %>
                <a href="#"><h4> <%= @kitap.isim %></h4></a>
                <div class="user_details">
                  <div class="float-left">
                 
                    
                  </div>
                  <div class="float-right mt-sm-0 mt-3">
                    <div class="media">
                      <div class="media-body">
                        <h5><%= @kitap.sayfa %></h5>
                       
                       
                        <br/>
                      </div>
                     
                    </div>
                  </div>
                  <p> <%= @kitap.ozet %><p/>
                </div>
                
                <div id="like">
                
                <strong>Beğeni sayısı: <%= @kitap.like.sayi %></strong>
               
                </div>
                 <button type="button" class="btn btn-light"><%= link_to " Beğen ", kitap_like_path(@kitap), remote: :true, method: :put %></button>
                <button type="button" class="btn btn-light"><%= link_to 'Edit', edit_kitap_path(@kitap) %> </button>
                <button type="button" class="btn btn-light"><%= link_to 'Back', kitaps_path %></button>
               

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Uygulama</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
 
    </head>

  <body>
 
    <%=render "shared/navbar"%>
    <br/><br/><br/>
    <%= yield %>
   
</html>

app/views/shared/_navbar.html.erb
<div id="wrapper" class="animate">
<nav class="navbar header-top fixed-top navbar-expand-lg navbar-dark bg-dark">
<span class="navbar-toggler-icon leftmenutrigger"></span>
<a class="navbar-brand" href="#">LOGO</a>
<button
class="navbar-toggler"
type="button"
data-toggle="collapse"
target="#navbarText" aria-controls="navbarText"
aria-expanded="false" aria-label="Toggle navigation">
<span class="navbar-toggler-icon"></span>
</button>
<div class="collapse navbar-collapse" id="navbarText">
<ul class="navbar-nav animate side-nav">
<li class="nav-item">
<a class="nav-link" href="#">Home
<span class="sr-only">(current)</span>
</a>
</li>
<li class="nav-item">
<a class="nav-link" href="#">Side Menu Items</a>
</li>
<li class="nav-item">
<a class="nav-link" href="#">Pricing</a>
</li>
</ul>
<ul class="navbar-nav ml-md-auto d-md-flex">
<li class="nav-item">
<a class="nav-link" href="#">Home
<span class="sr-only">(current)</span>
</a>
</li>
<li class="nav-item">
<a class="nav-link" href="#">Top Menu Items</a>
</li>
<li class="nav-item">
<a class="nav-link" href="#">Pricing</a>
</li>
</ul>
<p class="navbar-text pull-right"> <% if user_signed_in? %>
Logged in as <strong><%= current_user.email %></strong>.
<%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> | <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link' %>
<% else %>
<%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link' %> | <%= link_to "Login", new_user_session_path, :class => 'navbar-link' %>
<% end %> </p>
</div>
</nav>

app/views/yazars/_form.html.erb
<%= form_with(model: yazar, local: true) do |form| %>
  <% if yazar.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(yazar.errors.count, "error") %> prohibited this yazar from being saved:</h2>

      <ul>
      <% yazar.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :isim %>
    <%= form.text_field :isim %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/yazars/edit.html.erb
<h1>Editing Yazar</h1>

<%= render 'form', yazar: @yazar %>

<%= link_to 'Show', @yazar %> |
<%= link_to 'Back', yazars_path %>

app/views/yazars/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Yazars</h1>

<table>
  <thead>
    <tr>
      <th>Isim</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @yazars.each do |yazar| %>
      <tr>
        <td><%= yazar.isim %></td>
        <td><%= link_to 'Show', yazar %></td>
        <td><%= link_to 'Edit', edit_yazar_path(yazar) %></td>
        <td><%= link_to 'Destroy', yazar, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Yazar', new_yazar_path %>

app/views/yazars/new.html.erb
<h1>New Yazar</h1>

<%= render 'form', yazar: @yazar %>

<%= link_to 'Back', yazars_path %>

app/views/yazars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Isim:</strong>
  <%= @yazar.isim %>
</p>

<%= link_to 'Edit', edit_yazar_path(@yazar) %> |
<%= link_to 'Back', yazars_path %>